#+TITLE: ExaBayes User's Manual
#+AUTHOR: 
* Quick Start
* Installation
  After downloading the software package (e.g., exabayes-0.4.tar.gz),
  you will have to compile the source code. The following sections
  explain, how to do so. After compiling you obtain an executable
  called exabayes.    
** Requirements 
   ExaBayes requires a relatively recent c/c++ compiler that supports
   c++11 features. ExaBayes is confirmed to work with
   1. GCC version 4.6 or greater 
   2. Clang version 3.2 or greater
      
   For running ExaBayes, you need 
      

** Comfort build 
   The preferred way of compiling ExaBayes is to use the small
   *build.sh* script. If you need to have more control over the build
   process, consider the next two sections.

   Simple execution of the build script creates the sequential version
   of ExaBayes (called yggdrasil) and all pre- and post-processing
   tools in a build-folder.

#+BEGIN_SRC
  $ ./build.sh 
   [...] 
  $ ls build 
  asdsf  consense  credibleSet extractBips  obj-mpi  obj-seq  parser  postProcParam  yggdrasil
#+END_SRC
   
   For building the (parallel) mpi-version of ExaBayes (executable is
   called exabayes), please provide the name of the mpi-C compiler
   (usually mpicc) and mpi-C++ compiler (mpicxx,mpiCC or mpic++) as
   environment variable arguments. For instance: 

#+BEGIN_SRC
  $ ./build.sh CC=mpicc CXX=mpic++
  [...]
  $ ls build 
  exabayes
#+END_SRC

** Manual: Compiling the Sequential Version 
   To compile a sequential version of ExaBayes (called yggdrasil) and
   various pre- and post-processing tools, type
   #+BEGIN_SRC sh 
$ ./configure && make 
   #+END_SRC  
   If you have a multi-core machine, you can speed up the build
   process by adding -j<numProc> to the make command.
** Manual: Compiling the Parallel Version 
   For compiling the parallel mpi-version using the configure script,
   employ the command line below.

   You have to use a slightly different configure call and inform the
   configure script about your mpi compiler wrapper. These are usually
   called mpicc (c compiler) and mpicxx/mpiCC or mpic++ (c++
   compiler). For instance:
   #+BEGIN_SRC sh
$ ./configure --enable-mpi CC=mpicc CXX mpicxx  && make 
   #+END_SRC
   
* Command Line Options Explained
* The Configuration File 
* On Bayesian Analyses
* ExaBayes at Large: Invocations on Clusters/Supercomputers
* Notes on Reproducibility 
