
// TODO: we also need a header cleanup, just imported this from examl 
#ifdef WIN32
#include <direct.h>
#endif

#ifndef WIN32
#include <sys/times.h>
#include <sys/types.h>
#include <sys/time.h>
#include <unistd.h>
#endif

#include <math.h>
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdarg.h>
#include <limits.h>

#include <mpi.h>

#if ! (defined(__ppc) || defined(__powerpc__) || defined(PPC))
#include <xmmintrin.h>
/*
  special bug fix, enforces denormalized numbers to be flushed to zero,
  without this program is a tiny bit faster though.
  #include <emmintrin.h> 
  #define MM_DAZ_MASK    0x0040
  #define MM_DAZ_ON    0x0040
  #define MM_DAZ_OFF    0x0000
*/
#endif

/* use, if in productive mode */
/* #define PRODUCTIVE */

#include "axml.h"
#include "globalVariables.h"
#include "main-common.h"

#define _INCLUDE_DEFINITIONS
#include "globals.h"
#undef _INCLUDE_DEFINITIONS


void initAdef(analdef *adef);
void makeFileNames(void); 
void initializeTree(tree *tr, analdef *adef); 
void finalizeInfoFile(tree *tr, analdef *adef); 




int main(int argc, char *argv[])
{ 
  
  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &processID);
  MPI_Comm_size(MPI_COMM_WORLD, &processes);

  printf("\nThis is ExaML FINE-GRAIN MPI Process Number: %d\n", processID);   
  MPI_Barrier(MPI_COMM_WORLD);

  tree  *tr = (tree*)malloc(sizeof(tree));
  
  analdef *adef = (analdef*)malloc(sizeof(analdef));   

  /* 
     tell the CPU to ignore exceptions generated by denormalized floating point values.
     If this is not done, depending on the input data, the likelihood functions can exhibit 
     substantial run-time differences for vectors of equal length.
  */
    
#if ! (defined(__ppc) || defined(__powerpc__) || defined(PPC))
  _mm_setcsr( _mm_getcsr() | _MM_FLUSH_ZERO_ON);
#endif   

  /* get the start time */
   
  masterTime = gettime();         
    
  /* initialize the analysis parameters in struct adef to default values */
    
  initAdef(adef);

  /* parse command line arguments: this has a side effect on tr struct and adef struct variables */
  
  get_args(argc, argv, adef, tr); 
  
  /* generate the ExaML output file names and store them in strings */
    
  makeFileNames();

  initializeTree(tr, adef);                               
    
  if(processID == 0)  
    {
      /* TODO */
      /* printModelAndProgramInfo(tr, adef, argc, argv); */
      printBothOpen("Memory Saving Option: %s\n", (tr->saveMemory == TRUE)?"ENABLED":"DISABLED");   	             
    }  
                         
  /* 
     this will re-start ExaML exactly where it has left off from a checkpoint file,
     while checkpointing is important and has to be implemented for the library we should not worry about this right now 
  */

  /* not important, only used to keep track of total accumulated exec time 
     when checkpointing and restarts were used */
	
  if(processID == 0)
    accumulatedTime = 0.0;
	
  /* get the starting tree: here we just parse the tree passed via the command line 
     and do an initial likelihood computation traversal 
     which we maybe should skeip, TODO */
	       	
  getStartingTree(tr);     
	   	          
  /* 
     here we do an initial full tree traversal on the starting tree using the Felsenstein pruning algorithm 
     This should basically be the first call to the library that actually computes something :-)
  */
      
  evaluateGeneric(tr, tr->start, TRUE);	
	
  /* the treeEvaluate() function repeatedly iterates over the entire tree to optimize branch lengths until convergence */
      	
  treeEvaluate(tr, 1); 

  /* now start the ML search algorithm */
  mcmc( tr, adef );

      
  /* print some more nonsense into the ExaML_info file */
  
  if(processID == 0)
    finalizeInfoFile(tr, adef);

  
  /* return 0 which means that our unix program terminated correctly, the return value is not 1 here */

  MPI_Barrier(MPI_COMM_WORLD);
  MPI_Finalize();

  return 0;
}
